spring.application.name=exchange-proxy
server.port=8080

management.endpoints.web.exposure.include=health,info

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=exchange-proxy-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

exchange.kafka.topic=exchange-rates
exchange.kafka.partitions=3
exchange.kafka.replication-factor=1
exchange.api-url=https://api.exchangerate-api.com/v4/latest/USD
exchange.fetch-interval-ms=60000
exchange.elasticsearch.url=http://localhost:9200
exchange.elasticsearch.index=forex-data
